apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deadline-eviction-controller
rules:
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachineinstances"]
  verbs: ["get", "list", "watch", "patch", "update", "delete"]
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachineinstancemigrations"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachines"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
